name: Docs

on:
  push:
    paths:
      - '.github/workflows/docs.yaml'
      - 'dnsc.nimble'
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Gen docs
      run: nimble doc src/dnsc -y

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src/htmldocs
        tag_message: 'Deployment ${{ github.ref_name }}'
