name: Unit tests

on:
  push:
    paths:
      - '.github/workflows/test.yaml'
      - 'dnsc.nimble'
      - 'src/**'
      - 'tests/**'
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/test.yaml'
      - 'dnsc.nimble'
      - 'src/**'
      - 'tests/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
        nim-version:
          - '1.6.16'
          - 'stable'
          - 'devel'

    name: Test on ${{ matrix.nim-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v4
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-${{ matrix.nim-version }}
          restore-keys: |
            ${{ runner.os }}-choosenim-${{ matrix.nim-version }}-

      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v4
        with:
          path: ~/.nimble
          key: unit-tests-nimble

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.NIM_VERSION }}

      - name: Run unit test
        run: |
          nimble install -y
          nimble test -y
